import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        graytext: '#C9CFD4',
        header:'#191B1F',
        tiletextcolor: 'var(--tile-text-color)',
        lightgray: 'var(--light-gray)',
        gray: {
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)'
        },
        mango: {
          300: '#FFB300'
        },
        teal: {
          300: '#00CEAC',
          500: '#07838F'
        },
        green: {
          300: '#67CB67'
        },
        indigo: {
          300: '#B894FF'
        },
        sapBackgroundColor: 'var(--sapBackgroundColor)',
        sapBaseColor: 'var(--sapBaseColor)',
        sapButton_Accept_Background: 'var(--sapButton_Accept_Background)',
        sapButton_Accept_BorderColor: 'var(--sapButton_Accept_BorderColor)',
        sapButton_Accept_TextColor: 'var(--sapButton_Accept_TextColor)',
        sapButton_Accept_Hover_Background: 'var(--sapButton_Accept_Hover_Background)',
        sapButton_Accept_Hover_TextColor: 'var(--sapButton_Accept_Hover_TextColor)',
        sapButton_Emphasized_Background: 'var(--sapButton_Emphasized_Background)',
        sapButton_Emphasized_BorderColor: 'var(--sapButton_Emphasized_BorderColor)',
        sapButton_Emphasized_Hover_Background: 'var(--sapButton_Emphasized_Hover_Background)',
        sapButton_Emphasized_TextColor: 'var(--sapButton_Emphasized_TextColor)',
        sapButton_Emphasized_Hover_TextColor: 'var(--sapButton_Emphasized_Hover_TextColor)',
        sapButton_Reject_Background: 'var(--sapButton_Reject_Background)',
        sapButton_Reject_BorderColor: 'var(--sapButton_Reject_BorderColor)',
        sapButton_Reject_TextColor: 'var(--sapButton_Reject_TextColor)',
        sapButton_Reject_Hover_Background: 'var(--sapButton_Reject_Hover_Background)',
        sapButton_Attention_Background: 'var(--sapButton_Attention_Background)',
        sapButton_Attention_BorderColor: 'var(--sapButton_Attention_BorderColor)',
        sapButton_Attention_TextColor: 'var(--sapButton_Attention_TextColor)',
        sapButton_Attention_Hover_Background: 'var(--sapButton_Attention_Hover_Background)',
        sapInformationBackground: 'var(--sapInformationBackground)',
        sapSuccessBackground: 'var(--sapSuccessBackground)',
        sapSuccessColor: 'var(--sapSuccessColor)',
        sapErrorBackground: 'var(--sapErrorBackground)',
        sapErrorColor: 'var(--sapErrorColor)',
        sapInformationColor: 'var(--sapInformationColor)',
        sapWarningBackground: 'var(--sapWarningBackground)',
        sapWarningColor: 'var(--sapWarningColor)',
        sapField_Background: 'var(--sapField_Background)',
        sapField_TextColor: 'var(--sapField_TextColor)',
        sapField_Hover_Background: 'var(--sapField_Hover_Background)',
        sapField_BorderColor: 'var(--sapField_BorderColor)',
        sapPositiveColor: 'var(--sapPositiveColor)',
        sapNegativeColor: 'var(--sapNegativeColor)',
        sapCriticalColor: 'var(--sapCriticalColor)',
        sapGroup_TitleTextColor: 'var(--sapGroup_TitleTextColor)',
        sapBlockLayer_Background: 'var(--sapBlockLayer_Background)',
        sapTextColor: 'var(--sapTextColor)',
        sapTile_OverlayBackground: 'var(--sapTile_OverlayBackground)',
        sapShellColor: 'var(--sapShellColor)',
        sapHoverColor: 'var(--sapHoverColor)',
        sapContent_DisabledTextColor: 'var(--sapContent_DisabledTextColor)',
        sapField_ReadOnly_Background: 'var(--sapField_ReadOnly_Background)',
        sapField_ReadOnly_BackgroundStyle: 'var(--sapField_ReadOnly_BackgroundStyle)',
        sapField_ReadOnly_BorderColor: 'var(--sapField_ReadOnly_BorderColor)',
        sapField_ReadOnly_BorderStyle: 'var(--sapField_ReadOnly_BorderStyle)',
        sapActiveColor: 'var(--sapActiveColor)',
        sapShell_TextColor: 'var(--sapShell_TextColor)',
        sapHighlightColor: 'var(--sapHighlightColor)',
        sapAccentColor1: 'var(--sapAccentColor1)',
        sapAccentColor2: 'var(--sapAccentColor2)',
        sapAccentColor3: 'var(--sapAccentColor3)',
        sapAccentColor4: 'var(--sapAccentColor4)',
        sapAccentColor5: 'var(--sapAccentColor5)',
        sapAccentColor6: 'var(--sapAccentColor6)',
        sapAccentColor7: 'var(--sapAccentColor7)',
        sapAccentColor8: 'var(--sapAccentColor8)',
        sapAccentColor9: 'var(--sapAccentColor9)',
        sapAccentColor10: 'var(--sapAccentColor10)',
        sapField_Hover_BorderColor: 'var(--sapField_Hover_BorderColor)',
        sapButton_Active_TextColor: 'var(--sapButton_Active_TextColor)',
        sapLinkColor: 'var(--sapLinkColor)',
        sapLink_Hover_Color: 'var(--sapLink_Hover_Color)',
        sapBrandColor: 'var(--sapBrandColor)',
        sapShell_Background: 'var(--sapShell_Background)',
        sapIndicationColor_3: 'var(--sapIndicationColor_3)', 
        sapIndicationColor_8: 'var(--sapIndicationColor_8)',
        sapIndicationColor_6: 'var(--sapIndicationColor_6)',
        sapIndicationColor_7: 'var(--sapIndicationColor_7)',
        sapIndicationColor_5: 'var(--sapIndicationColor_5)',
        sapButton_Success_TextColor: 'var(--sapButton_Success_TextColor)',
        sapField_InvalidColor: 'var(--sapField_InvalidColor)',
      }
    },
  },
  plugins: [],
};
export default config;
